Repository team-MonoPad/MonoPad, pull requests merged in 2020-10, with the labels that each got.

#24 update detail movie set
  app/src/main/java/com/project/monopad/model/network/MovieInfoResultResponse.kt
  app/src/main/java/com/project/monopad/model/network/dto/Dates.kt
  app/src/main/java/com/project/monopad/model/network/dto/Genre.kt
  app/src/main/java/com/project/monopad/model/network/dto/User.kt
  app/src/main/java/com/project/monopad/model/network/response/MovieDetailResponse.kt
  app/src/main/java/com/project/monopad/model/network/response/MovieInfoResponse.kt
  app/src/main/java/com/project/monopad/model/network/response/MovieInfoResultResponse.kt
  app/src/main/java/com/project/monopad/model/network/response/OtherMovieInfoResponse.kt
  app/src/main/java/com/project/monopad/network/remote/api/MovieRepoApi.kt
  app/src/main/java/com/project/monopad/network/remote/datasource/MovieRemoteDataSource.kt
  app/src/main/java/com/project/monopad/network/remote/datasource/MovieRemoteDataSourceImpl.kt
  app/src/main/java/com/project/monopad/network/repository/MovieRepo.kt
  app/src/main/java/com/project/monopad/network/repository/MovieRepoImpl.kt
Labels: TODO

#35 #34 - add Google Login
  app/src/main/java/com/project/monopad/di/DiModule.kt
  app/src/main/java/com/project/monopad/model/network/User.kt
  app/src/main/java/com/project/monopad/network/remote/api/UserApiClient.kt
  app/src/main/java/com/project/monopad/network/remote/datasource/UserRemoteDataSource.kt
  app/src/main/java/com/project/monopad/network/remote/datasource/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/project/monopad/network/repository/UserRepo.kt
  app/src/main/java/com/project/monopad/network/repository/UserRepoImpl.kt
  app/src/main/java/com/project/monopad/ui/view/login/LoginActivity.kt
  app/src/main/java/com/project/monopad/ui/view/login/RegisterActivity.kt
  app/src/main/java/com/project/monopad/ui/viewmodel/LoginViewModel.kt
  app/src/main/java/com/project/monopad/ui/viewmodel/RegisterViewModel.kt
  app/src/main/java/com/project/monopad/util/LoginMode.kt
  app/src/main/java/com/project/monopad/util/PreferenceManager.kt
  app/src/main/res/layout/activity_login.xml
Labels: review required

#61 Feature/26 calendar ui setting ver.month
  .idea/misc.xml
  app/src/main/java/com/project/monopad/di/DiModule.kt
  app/src/main/java/com/project/monopad/model/entity/Review.kt
  app/src/main/java/com/project/monopad/network/local/converter/DateConverter.kt
  app/src/main/java/com/project/monopad/network/local/database/DiaryDatabase.kt
  app/src/main/java/com/project/monopad/ui/imagebind/ReviewBinding.kt
  app/src/main/java/com/project/monopad/ui/view/custom/bottomsheetdialog/BottomSheetListAdapter.kt
  app/src/main/java/com/project/monopad/ui/view/custom/bottomsheetdialog/DiaryListBottomSheetFragment.kt
  app/src/main/java/com/project/monopad/ui/view/custom/calendar/CalendarAdapter.kt
  app/src/main/java/com/project/monopad/ui/view/custom/calendar/CalendarView.kt
  app/src/main/java/com/project/monopad/ui/view/diary/BottomSheetListAdapter.kt
  app/src/main/java/com/project/monopad/ui/view/diary/DiaryFragment.kt
  app/src/main/java/com/project/monopad/ui/viewmodel/DiaryViewModel.kt
  app/src/main/java/com/project/monopad/util/CalendarUtil.kt
  app/src/main/java/com/project/monopad/util/DateUtil.kt
  app/src/main/java/com/project/monopad/util/DayState.kt
  app/src/main/java/com/project/monopad/util/DownloadUtil.kt
  app/src/main/res/drawable/border_black.xml
  app/src/main/res/drawable/border_gray.xml
  app/src/main/res/drawable/ic_baseline_movie_24.xml
  app/src/main/res/drawable/toolbar_bg.xml
  app/src/main/res/layout/calendar_item_layout.xml
  app/src/main/res/layout/calendar_top_layout.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/fragment_diary_list_bottom_sheet.xml
  app/src/main/res/layout/item_bs_list_movie.xml
  app/src/main/res/layout/item_calendar_day.xml
Labels: review required

#78 Feature/74 repository pattern update
  app/src/main/java/com/project/monopad/di/RepositoryModule.kt
  app/src/main/java/com/project/monopad/di/ViewModelModule.kt
  app/src/main/java/com/project/monopad/network/local/LocalDataSource.kt
  app/src/main/java/com/project/monopad/network/local/database/DiaryDao.kt
  app/src/main/java/com/project/monopad/network/repository/ReviewRepo.kt
  app/src/main/java/com/project/monopad/network/repository/ReviewRepoImpl.kt
  app/src/main/java/com/project/monopad/ui/viewmodel/DiaryViewModel.kt
Labels: review required, wodbs135
